import { pgTable, text, serial, integer, boolean, timestamp, jsonb, decimal, pgEnum } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { relations } from "drizzle-orm";

// Enums
export const caseStatusEnum = pgEnum("case_status", ["nuevo", "en_proceso", "denunciado", "resuelto", "cerrado"]);
export const crimeTypeEnum = pgEnum("crime_type", ["phishing", "hackeo_whatsapp", "hackeo_email", "extorsion", "otro"]);

// Users table (Victims/Admin)
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  telegramId: text("telegram_id").unique(),
  fullName: text("full_name"),
  identificationNumber: text("identification_number"),
  age: integer("age"),
  profession: text("profession"),
  residenceCity: text("residence_city"),
  residenceCountry: text("residence_country"),
  phoneNumber: text("phone_number"),
  role: text("role").default("user"), // user, admin
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Cases table
export const cases = pgTable("cases", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  caseNumber: text("case_number").unique().notNull(),
  type: crimeTypeEnum("type"),
  status: caseStatusEnum("status").default("nuevo"),
  description: text("description"),
  incidentDate: timestamp("incident_date"),
  amountLost: decimal("amount_lost", { precision: 12, scale: 2 }), // Supports large amounts
  suspectNumber: text("suspect_number"),
  bankEntity: text("bank_entity"),
  sharedOtp: boolean("shared_otp").default(false),
  transferMade: boolean("transfer_made").default(false),
  appCompromised: text("app_compromised"),
  deviceAffected: text("device_affected"),
  country: text("country"),
  city: text("city"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// Evidence table
export const evidences = pgTable("evidences", {
  id: serial("id").primaryKey(),
  caseId: integer("case_id").references(() => cases.id),
  type: text("type"), // screenshot, document, url, audio, video
  filePath: text("file_path"),
  fileId: text("file_id"), // telegram file id
  description: text("description"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Bot Interactions Log
export const botInteractions = pgTable("bot_interactions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  telegramId: text("telegram_id"),
  message: text("message"),
  actionType: text("action_type"),
  metadata: jsonb("metadata"),
  timestamp: timestamp("timestamp").defaultNow(),
});

// Reported Numbers (Fraud Database)
export const reportedNumbers = pgTable("reported_numbers", {
  id: serial("id").primaryKey(),
  number: text("number").unique(),
  reportCount: integer("report_count").default(1),
  fraudType: text("fraud_type"),
  originCountry: text("origin_country"),
  lastReportedAt: timestamp("last_reported_at").defaultNow(),
});

// Relations
export const usersRelations = relations(users, ({ many }) => ({
  cases: many(cases),
  interactions: many(botInteractions),
}));

export const casesRelations = relations(cases, ({ one, many }) => ({
  user: one(users, {
    fields: [cases.userId],
    references: [users.id],
  }),
  evidences: many(evidences),
}));

export const evidencesRelations = relations(evidences, ({ one }) => ({
  case: one(cases, {
    fields: [evidences.caseId],
    references: [cases.id],
  }),
}));

// Schemas
export const insertUserSchema = createInsertSchema(users).omit({ id: true, createdAt: true, updatedAt: true });
export const insertCaseSchema = createInsertSchema(cases).omit({ id: true, createdAt: true, updatedAt: true, caseNumber: true }); // caseNumber generated by backend
export const insertEvidenceSchema = createInsertSchema(evidences).omit({ id: true, createdAt: true });
export const insertBotInteractionSchema = createInsertSchema(botInteractions).omit({ id: true, timestamp: true });
export const insertReportedNumberSchema = createInsertSchema(reportedNumbers).omit({ id: true, lastReportedAt: true });

// Types
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type Case = typeof cases.$inferSelect;
export type InsertCase = z.infer<typeof insertCaseSchema>;
export type Evidence = typeof evidences.$inferSelect;
export type BotInteraction = typeof botInteractions.$inferSelect;
export type ReportedNumber = typeof reportedNumbers.$inferSelect;
